### ISSUE TITLE
大佬 网卡用的哪个 ？

### ISSUE THREAD

**Issue by shen-lan** [awebhay/hackintosh_B365M_Pro4#1]
拆机网卡 ？无线蓝牙都正常吗

**Comment by travisdevpanel** [comment]
I use wifi and bluetooth integrated card version 94331csax. All good include handrop, airdrop.

**Comment by travisdevpanel** [comment]
![image](https://user-images.githubusercontent.com/58158070/83960386-6e83d500-a8b2-11ea-9b3a-06b7868a16d4.png)

**Comment by shen-lan** [comment]
Thanks! 😘
